### ISSUE TITLE
Support all ament linters

### ISSUE THREAD

**Issue by patrick-5546** [athackst/vscode-ament-task-provider#130]
I noticed that this extension only supports a subset of ament linters: https://github.com/ament/ament_lint/.

Would it be possible to add problem matchers for the rest of them? If it is a lot of work, would you accept PRs to add problem matchers for the linters that I want to use? I am specifically interested in clang tidy and mypy.

**Comment by athackst** [comment]
I would definitely accept PRs!

**Comment by patrick-5546** [comment]
Great! Can you give me a brief overview of what would have to be done to add a problem matcher?

**Comment by athackst** [comment]
I made some instructions here -> https://github.com/athackst/vscode-ament-task-provider/blob/main/How-to-Add.md

**Comment by patrick-5546** [comment]
Thanks! I'll close this issue then
