### ISSUE TITLE
Add parameters to linter call

### ISSUE THREAD

**Issue by rosterloh** [athackst/vscode-ament-task-provider#93]
Thanks for this extension, it's very helpful. I was wondering if you had any plans to support adding parameters to a linter call. For example `ament_cpplint --filters=-legal/copyright`?

**Comment by athackst** [comment]
Sure, I can probably add parameters

**Comment by rosterloh** [comment]
Looking at the code I thought it was checking the input string against a dictionary and adding parameters wouldn't work but the following seems to work as expected
```{
  "version": "2.0.0",
  "tasks": [
    {
      "type": "ament",
      "task": "cpplint --filters=-legal/copyright",
      "path": "src/",
      "problemMatcher": [
        "$ament_cppcheck"
      ],
      "label": "ament: cppcheck"
    }
  ]
}

```
